# Este archivo NO se sube a GitHub (agrégalo al .gitignore)
# En Clever Cloud, este archivo se genera automáticamente desde las variables de entorno
# O puedes subirlo manualmente si tu repo es privado

[db]
host     = "bmffi0bgsqnener2omcu-mysql.services.clever-cloud.com"
database = "bmffi0bgsqnener2omcu"
user     = "uo8vbdsnvm2ojwta"
password = "aXSKib5oxXDEwjlozeQP"
port     = 3306
